# Generated by Django 6.0.3 on 2026-04-03 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacklogSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_key', models.CharField(max_length=100, unique=True)),
                ('domain', models.CharField(choices=[('backlog.jp', 'backlog.jp'), ('backlog.com', 'backlog.com')], default='backlog.jp', max_length=20)),
                ('api_key', models.CharField(max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'backlog_spaces',
            },
        ),
        migrations.CreateModel(
            name='BacklogUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backlog_id', models.PositiveBigIntegerField()),
                ('user_id_str', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('mail_address', models.EmailField(blank=True, default='', max_length=254)),
                ('is_myself', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.backlogspace')),
            ],
            options={
                'db_table': 'backlog_users',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backlog_id', models.PositiveBigIntegerField()),
                ('project_key', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.backlogspace')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backlog_id', models.PositiveBigIntegerField()),
                ('issue_key', models.CharField(db_index=True, max_length=50)),
                ('summary', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('issue_type', models.CharField(blank=True, default='', max_length=100)),
                ('status_name', models.CharField(db_index=True, max_length=100)),
                ('status_id', models.PositiveIntegerField(default=0)),
                ('priority_name', models.CharField(blank=True, default='', max_length=50)),
                ('priority_id', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('estimated_hours', models.FloatField(blank=True, null=True)),
                ('actual_hours', models.FloatField(blank=True, null=True)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('last_comment_at', models.DateTimeField(blank=True, null=True)),
                ('backlog_created', models.DateTimeField()),
                ('backlog_updated', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_overdue', models.BooleanField(db_index=True, default=False)),
                ('is_stagnant', models.BooleanField(db_index=True, default=False)),
                ('stagnant_days', models.PositiveIntegerField(default=0)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='core.backloguser')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to='core.backloguser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.project')),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backlog_id', models.PositiveBigIntegerField()),
                ('content', models.TextField(blank=True, default='')),
                ('backlog_created', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_comments', to='core.backloguser')),
                ('mentioned_users', models.ManyToManyField(blank=True, related_name='mentioned_in_comments', to='core.backloguser')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.ticket')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.AddConstraint(
            model_name='backloguser',
            constraint=models.UniqueConstraint(fields=('space', 'backlog_id'), name='uq_space_backlog_user'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('space', 'backlog_id'), name='uq_space_project'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['due_date'], name='tickets_due_dat_c75c11_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assignee', 'status_name'], name='tickets_assigne_73affc_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('project', 'backlog_id'), name='uq_project_ticket'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('ticket', 'backlog_id'), name='uq_ticket_comment'),
        ),
    ]
