# Generated by Django 6.0.3 on 2026-04-03 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='方針書 Markdown')),
                ('model_used', models.CharField(max_length=50)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec', to='core.ticket')),
            ],
            options={
                'db_table': 'spec_documents',
            },
        ),
        migrations.CreateModel(
            name='TicketEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_completeness_score', models.PositiveIntegerField(help_text='情報充足度 0-100')),
                ('missing_items', models.JSONField(default=list, help_text='欠損情報リスト')),
                ('spec_readiness', models.CharField(choices=[('ready', '作成可能'), ('partial', '一部不足'), ('not_ready', '情報不足')], help_text='方針書作成可否', max_length=20)),
                ('schedule_feasibility', models.CharField(choices=[('feasible', '妥当'), ('risky', 'リスクあり'), ('unrealistic', '非現実的'), ('unknown', '判定不可')], help_text='日程妥当性', max_length=20)),
                ('schedule_comment', models.TextField(blank=True, default='', help_text='日程に関するコメント')),
                ('summary', models.TextField(help_text='評価サマリ')),
                ('pr_urls', models.JSONField(default=list, help_text='検出されたPR URL一覧')),
                ('model_used', models.CharField(max_length=50)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='core.ticket')),
            ],
            options={
                'db_table': 'ticket_evaluations',
            },
        ),
    ]
