# Generated by Django 6.0.3 on 2026-04-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_specdocument_ticketevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketevaluation',
            name='ambiguity_score',
            field=models.PositiveIntegerField(default=0, help_text='仕様曖昧度 0-100'),
        ),
        migrations.AddField(
            model_name='ticketevaluation',
            name='coordination_cost_score',
            field=models.PositiveIntegerField(default=0, help_text='調整コスト 0-100'),
        ),
        migrations.AddField(
            model_name='ticketevaluation',
            name='difficulty_comment',
            field=models.TextField(blank=True, default='', help_text='難易度に関する補足コメント'),
        ),
        migrations.AddField(
            model_name='ticketevaluation',
            name='impact_scope_score',
            field=models.PositiveIntegerField(default=0, help_text='影響範囲 0-100'),
        ),
        migrations.AddField(
            model_name='ticketevaluation',
            name='overall_difficulty_score',
            field=models.PositiveIntegerField(default=0, help_text='総合難易度 0-100'),
        ),
        migrations.AddField(
            model_name='ticketevaluation',
            name='query_complexity_score',
            field=models.PositiveIntegerField(default=0, help_text='クエリ複雑度 0-100'),
        ),
        migrations.AddField(
            model_name='ticketevaluation',
            name='regression_risk_score',
            field=models.PositiveIntegerField(default=0, help_text='リグレッションリスク 0-100'),
        ),
        migrations.AddField(
            model_name='ticketevaluation',
            name='verification_difficulty_score',
            field=models.PositiveIntegerField(default=0, help_text='テスト・検証難度 0-100'),
        ),
    ]
