# Generated by Django 6.0.3 on 2026-04-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ticketevaluation_ambiguity_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'excluded_statuses',
                'ordering': ['status_name'],
            },
        ),
    ]
