# Generated by Django 6.0.3 on 2026-04-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_excluded_status_per_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketevaluation',
            name='estimated_breakdown',
            field=models.JSONField(default=list, help_text='工数内訳 [{phase, days, note}]'),
        ),
        migrations.AddField(
            model_name='ticketevaluation',
            name='estimated_days',
            field=models.FloatField(default=0, help_text='推定工数（人日）'),
        ),
    ]
