# Generated by Django 6.0.3 on 2026-04-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_estimated_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketevaluation',
            name='resolution_comment',
            field=models.TextField(blank=True, default='', help_text='対処区分の根拠'),
        ),
        migrations.AddField(
            model_name='ticketevaluation',
            name='resolution_type',
            field=models.CharField(choices=[('data_fix', 'データ修正'), ('code_fix', 'コード修正'), ('config_change', '設定変更'), ('investigation', '調査のみ'), ('mixed', '複合'), ('unknown', '判定不可')], default='unknown', help_text='対処区分', max_length=20),
        ),
    ]
