# Generated by Django 6.0.3 on 2026-04-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_comment_attachments_and_eval_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='custom_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
