# Generated by Django 6.0.3 on 2026-04-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ticket_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_at',
            field=models.DateTimeField(blank=True, help_text='Backlog 投稿日時 (null=未投稿)', null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='source',
            field=models.CharField(choices=[('synced', '同期'), ('ai', 'AI生成'), ('manual', '手動作成')], default='synced', max_length=20),
        ),
        migrations.AddField(
            model_name='comment',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="タグ配列 (例: ['spec', 'pr'])"),
        ),
        migrations.DeleteModel(
            name='SpecDocument',
        ),
    ]
