# Generated by Django 6.0.3 on 2026-04-04 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_comment_tags_and_remove_spec'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('local_path', models.CharField(help_text='ローカルディレクトリの絶対パス', max_length=500)),
                ('match_field', models.CharField(blank=True, help_text='マッチ対象のカスタム属性名（例: 対象システム）。空なら無条件マッチ', max_length=200, null=True)),
                ('match_value', models.CharField(blank=True, help_text='マッチする値（例: フロントエンド）', max_length=200, null=True)),
                ('description', models.CharField(blank=True, default='', help_text='技術スタック等のメモ', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='core.project')),
            ],
            options={
                'db_table': 'code_repositories',
                'ordering': ['project', 'name'],
            },
        ),
    ]
