# Generated by Django 6.0.3 on 2026-04-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_coderepository'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='previous_status_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
