# Generated by Django 6.0.3 on 2026-04-04 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_status_change_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('pinned_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pin', to='core.ticket')),
            ],
            options={
                'db_table': 'pinned_tickets',
                'ordering': ['-pinned_at'],
            },
        ),
    ]
