# Generated by Django 6.0.3 on 2026-04-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_fix_synced_comment_posted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(help_text='Jira サイト名（例: mycompany）', max_length=200, unique=True)),
                ('base_url', models.URLField(help_text='Jira サイトの URL（例: https://mycompany.atlassian.net）', max_length=500)),
                ('user_email', models.EmailField(help_text='Jira ログイン用メールアドレス', max_length=254)),
                ('api_token', models.CharField(help_text='Jira API トークン', max_length=500)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jira_spaces',
            },
        ),
    ]
