# Generated by Django 6.0.3 on 2026-04-05 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_jira_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='backloguser',
            name='jira_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.jiraspace'),
        ),
        migrations.AddField(
            model_name='project',
            name='jira_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.jiraspace'),
        ),
        migrations.AlterField(
            model_name='backloguser',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.backlogspace'),
        ),
        migrations.AlterField(
            model_name='project',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.backlogspace'),
        ),
    ]
