# Generated by Django 6.0.3 on 2026-04-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_parent_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlogspace',
            name='sync_interval_minutes',
            field=models.PositiveIntegerField(default=0, help_text='自動同期間隔（分）。0=手動のみ'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_watched',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
