from django.urls import path

from apps.core.views import (
    BackgroundTaskDetailView,
    BackgroundTaskStatusView,
    BacklogSpaceDetailView,
    BulkPostCommentsView,
    JiraSpaceDetailView,
    JiraSpaceListCreateView,
    JiraSyncTriggerView,
    PinnedTicketDestroyView,
    PinnedTicketListCreateView,
    UnpostedSpecsView,
    BacklogSpaceListCreateView,
    BacklogUserListView,
    BacklogUserUpdateView,
    BrowseDirsView,
    CodeRepositoryDetailView,
    CodeRepositoryListCreateView,
    CommentCreateView,
    CommentDeleteView,
    CommentPostToBacklogView,
    CommentUpdateTagsView,
    CommentUpdateView,
    DashboardStatsView,
    ExcludedStatusDestroyView,
    ExcludedStatusListCreateView,
    ProjectListView,
    StatusNameListView,
    SyncTriggerView,
    TicketDetailView,
    TicketEvaluateView,
    TicketExportView,
    TicketGenerateSpecView,
    TicketListView,
)

urlpatterns = [
    path("dashboard/stats/", DashboardStatsView.as_view(), name="dashboard-stats"),
    path("tickets/", TicketListView.as_view(), name="ticket-list"),
    path("tickets/export/", TicketExportView.as_view(), name="ticket-export"),
    path("tickets/<int:pk>/", TicketDetailView.as_view(), name="ticket-detail"),
    path("tickets/<int:pk>/evaluate/", TicketEvaluateView.as_view(), name="ticket-evaluate"),
    path("tickets/<int:pk>/generate-spec/", TicketGenerateSpecView.as_view(), name="ticket-generate-spec"),
    path("tickets/<int:pk>/comments/", CommentCreateView.as_view(), name="comment-create"),
    path("tickets/<int:pk>/comments/<int:comment_pk>/tags/", CommentUpdateTagsView.as_view(), name="comment-update-tags"),
    path("tickets/<int:pk>/comments/<int:comment_pk>/post/", CommentPostToBacklogView.as_view(), name="comment-post-to-backlog"),
    path("tickets/<int:pk>/comments/<int:comment_pk>/edit/", CommentUpdateView.as_view(), name="comment-update"),
    path("tickets/<int:pk>/comments/<int:comment_pk>/", CommentDeleteView.as_view(), name="comment-delete"),
    path("projects/", ProjectListView.as_view(), name="project-list"),
    path("users/", BacklogUserListView.as_view(), name="user-list"),
    path("users/<int:pk>/", BacklogUserUpdateView.as_view(), name="user-detail"),
    path("status-names/", StatusNameListView.as_view(), name="status-name-list"),
    path("spaces/", BacklogSpaceListCreateView.as_view(), name="space-list"),
    path("spaces/<int:pk>/", BacklogSpaceDetailView.as_view(), name="space-detail"),
    path("jira-spaces/", JiraSpaceListCreateView.as_view(), name="jira-space-list"),
    path("jira-spaces/<int:pk>/", JiraSpaceDetailView.as_view(), name="jira-space-detail"),
    path("jira-spaces/<int:pk>/sync/", JiraSyncTriggerView.as_view(), name="jira-sync-trigger"),
    path("excluded-statuses/", ExcludedStatusListCreateView.as_view(), name="excluded-status-list"),
    path("excluded-statuses/<int:pk>/", ExcludedStatusDestroyView.as_view(), name="excluded-status-detail"),
    path("sync/", SyncTriggerView.as_view(), name="sync-trigger"),
    path("comments/unposted-specs/", UnpostedSpecsView.as_view(), name="unposted-specs"),
    path("comments/bulk-post/", BulkPostCommentsView.as_view(), name="comment-bulk-post"),
    path("pinned-tickets/", PinnedTicketListCreateView.as_view(), name="pinned-ticket-list"),
    path("pinned-tickets/<int:pk>/", PinnedTicketDestroyView.as_view(), name="pinned-ticket-detail"),
    path("repositories/", CodeRepositoryListCreateView.as_view(), name="repository-list"),
    path("repositories/<int:pk>/", CodeRepositoryDetailView.as_view(), name="repository-detail"),
    path("browse-dirs/", BrowseDirsView.as_view(), name="browse-dirs"),
    path("tasks/", BackgroundTaskStatusView.as_view(), name="task-list"),
    path("tasks/<str:task_id>/", BackgroundTaskDetailView.as_view(), name="task-detail"),
]
